### ISSUE TITLE
I could not find the pb_schema.json

### ISSUE THREAD

**Issue by thedittmer** [Mind-thatsall/blog-svelte-pocketbase#1]
I would like to try this, but I was not able to import the collections into pocketbase. I did not find the pb_schema.json file in the root directory of the project.

**Comment by okzmo** [comment]
Hello ! I just added the pb_schema.json (with some mock data in it) to the root directory. Sorry for the inconvenience. 

PS : Thanks for your interest in this beginner project 😄
